<?php

namespace App\Controllers\Backend;

use App\Constants\CollectionStatus;
use App\Constants\ContentStatus;
use App\Constants\TagStatus;
use App\Core\Config;
use App\Helpers\UrlHelper;
use App\Models\Collection;
use App\Models\Content;
use App\Models\ContentType;
use App\Models\Tag;

class SitemapController extends BackendController
{
    // --- 配置区域 ---
    public $base_url = 'https://lib00.com';
    public $items_per_page = 4;

    /**
     * 定义 before action 过滤器配置
     * 子类重写此方法来配置过滤器
     *
     * @return array 过滤器配置数组
     */
    protected function beforeActionFilters(): array
    {
        //return [] for skip auth check
        return [];

    }

    public function init()
    {
        $this->base_url = Config::get('request.base_url');
        $this->items_per_page = Config::get('pagination.per_page');

        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 公共入口方法，生成并输出完整的Sitemap
     */
    public function generate(): void
    {
        header('Content-Type: application/xml; charset=utf-8');

        $this->generateHeader();

        $this->generateHomepageUrls();
        $this->generateContentListUrls();
        $this->generateFilteredListUrls();

        $this->generateFooter();
    }

    // ===================================================================
    //  XML 生成辅助方法 (保持不变)
    // ===================================================================

    private function generateHeader(): void
    {
        echo '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
        echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">' . "\n";
    }

    private function generateFooter(): void
    {
        echo '</urlset>';
    }

    private function generateUrlEntry($zh_url, $en_url, $lastmod, $changefreq, $priority): void
    {
        $zh_url_escaped = htmlspecialchars($zh_url, ENT_XML1, 'UTF-8');
        $en_url_escaped = htmlspecialchars($en_url, ENT_XML1, 'UTF-8');

        echo "    <url>\n";
        echo "        <loc>{$zh_url_escaped}</loc>\n";
        echo "        <xhtml:link rel=\"alternate\" hreflang=\"zh\" href=\"{$zh_url_escaped}\"/>\n";
        echo "        <xhtml:link rel=\"alternate\" hreflang=\"en\" href=\"{$en_url_escaped}\"/>\n";
        echo "        <lastmod>{$lastmod}</lastmod>\n";
        echo "        <changefreq>{$changefreq}</changefreq>\n";
        echo "        <priority>{$priority}</priority>\n";
        echo "    </url>\n";
    }

    // ===================================================================
    //  URL 生成逻辑 (已重构)
    // ===================================================================

    private function generateHomepageUrls(): void
    {
        $homepage_cn = $this->base_url . '/zh/content';
        $homepage_en = $this->base_url . '/en/content';
        $this->generateUrlEntry($homepage_cn, $homepage_en, date('c'), 'daily', 1.0);
    }

    private function generateContentListUrls(): void
    {
        $contents = Content::where(['status_id' => ContentStatus::PUBLISHED->value])->whereRaw('pub_at < NOW()')->all();

        /**
         * @var $oneContent Content
         */
        foreach ($contents as $oneContent) {
            $detail_url_cn = $this->base_url . "/zh/content/{$oneContent->id}/". UrlHelper::formatString($oneContent->title_en);
            $detail_url_en = $this->base_url . "/en/content/{$oneContent->id}/". UrlHelper::formatString($oneContent->title_en);
            $lastmod = date('c', strtotime($oneContent->updated_at));

            $ct_name_en = 'Article';
            if ($oneContent->content_type_id < 10) {
                $ct_name_en = $oneContent->contentType->title_en;
            }
            $params = self::calculateSitemapParams($oneContent->updated_at, $ct_name_en);

            $this->generateUrlEntry($detail_url_cn, $detail_url_en, $lastmod, $params['changefreq'], $params['priority']);
        }
    }

    private function generateFilteredListUrls(): void
    {
        // 1. 处理 Tags
        $tags = Tag::findAll(['status_id'=>TagStatus::ENABLED->value]);
        foreach ($tags as $oneTag){
            $list_url_cn = $this->base_url . Tag::buildListUrl($oneTag->id, $oneTag->name_en,'zh');
            $list_url_en = $this->base_url . Tag::buildListUrl($oneTag->id, $oneTag->name_en, 'en');

            $lastmod = date('c', strtotime($oneTag->updated_at));
            $params = self::calculateSitemapParams($oneTag->updated_at, 'tag_list');
            $this->generateUrlEntry($list_url_cn, $list_url_en, $lastmod, $params['changefreq'], $params['priority']);
        }

        // 2. 处理 Collections
        $collections = Collection::findAll(['status_id'=>CollectionStatus::ENABLED->value]);
        foreach ($collections as $oneCollection) {
            $list_url_cn = $this->base_url  . Collection::buildListUrl($oneCollection->id, $oneCollection->name_en, 'zh');
            $list_url_en = $this->base_url  . Collection::buildListUrl($oneCollection->id, $oneCollection->name_en, 'en');

            $lastmod = date('c', strtotime($oneCollection->updated_at));
            $params = self::calculateSitemapParams($oneCollection->updated_at, 'collection_list');
            $this->generateUrlEntry($list_url_cn, $list_url_en, $lastmod, $params['changefreq'], $params['priority']);
        }

        /**
         * @var $oneContentType ContentType
         * @var $lastChangedConten111t1 Content
         */
        // 3. 处理 Content Types (来自常量)
        foreach (ContentType::loadList([], ['id'=>'id', 'name_en'=>'name_en']) as $oneContentType) {

            // load this type's last updated content
            $lastChangedContent = Content::where(['content_type_id'=>$oneContentType['id']])->orderBy('updated_at DESC')->one();



            //for no content type, use 2025-01-01 as last update date.
            $lastDate = '2025-01-01 00:00:00';

            if ($lastChangedContent) {
                $lastDate = $lastChangedContent->updated_at;
            }
            $lastmod = date('c', strtotime($lastDate));
            $params = self::calculateSitemapParams($lastDate, 'content_type_list');

            $list_url_cn = $this->base_url . "/zh/content-type/{$oneContentType['id']}/".UrlHelper::formatString($oneContentType['name_en']);
            $list_url_en = $this->base_url . "/en/content-type/{$oneContentType['id']}/".UrlHelper::formatString($oneContentType['name_en']);
            $this->generateUrlEntry($list_url_cn, $list_url_en, $lastmod, $params['changefreq'], $params['priority']);
        }
    }

    /**
     * 根据总数生成分页URL条目的辅助函数
     * @param string $paramName   URL参数名 ('tag_id', 'collection_id'...)
     * @param int    $id          参数值
     * @param int    $totalItems  该分类下的项目总数
     */
    private function generatePaginatedUrls($paramName, $id, $totalItems): void
    {
        if ($totalItems > 0) {
            $totalPages = ceil($totalItems / $this->items_per_page);
            for ($page = 1; $page <= $totalPages; $page++) {
                $list_url_cn = $this->base_url . "/content?{$paramName}={$id}&page={$page}&lang=zh";
                $list_url_en = $this->base_url . "/content?{$paramName}={$id}&page={$page}&lang=en";
                $this->generateUrlEntry($list_url_cn, $list_url_en, date('c'), 'daily', 0.9);
            }
        }
    }

    /**
     * A reusable helper to calculate sitemap priority and changefreq.
     *
     * @param string $lastModifiedDate The last modification date string (e.g., from updated_at).
     * @param string $pageType A string identifier for the page type (e.g., 'article', 'tag_list', 'collection_list').
     * @return array ['priority' => float, 'changefreq' => string]
     */
    public static function calculateSitemapParams(string $lastModifiedDate, string $pageType): array
    {
        $updateTimestamp = strtotime($lastModifiedDate);
        $ageInSeconds = time() - $updateTimestamp;

        // --- 1. Determine Change Frequency (mostly time-based) ---
        $oneMonth = 30 * 24 * 60 * 60;
        $oneYear = 365 * 24 * 60 * 60;

        if ($ageInSeconds < $oneMonth) {
            $changefreq = 'weekly';
        } elseif ($ageInSeconds > $oneYear) {
            $changefreq = 'yearly';
        } else {
            $changefreq = 'monthly';
        }

        // --- 2. Determine Priority (mostly type-based, with time adjustment) ---
        $priority = 0.5; // Default priority
        $threeMonths = 3 * $oneMonth;

        switch ($pageType) {
            // High-level navigation pages
            case 'collection_list':
            case 'content_type_list':
                $priority = ($ageInSeconds < $threeMonths) ? 0.9 : 0.7;
                break;

            // Mid-level navigation pages
            case 'tag_list':
                $priority = ($ageInSeconds < $threeMonths) ? 0.7 : 0.5;
                break;

            // Content detail pages
            case 'Announcement':
                $priority = ($ageInSeconds < $threeMonths) ? 0.8 : 0.4;
                break;

            case 'Article':
            case 'Video':
                if ($ageInSeconds < $threeMonths) {
                    $priority = 0.7;
                } elseif ($ageInSeconds > $oneYear) {
                    $priority = 0.3;
                } else {
                    $priority = 0.5;
                }
                break;
        }

        return [
            'priority'   => $priority,
            'changefreq' => $changefreq,
        ];
    }
}